 1.Five differences between optuna and grid search and random search
 ----------------------------------
 https://docs.google.com/spreadsheets/d/1fGzAw5wo_g4peHuKEjRfg_EqiiFITpBxy7Gv80HDa24/edit#gid=0
 

2.Classificaiton dataset example  to check  the accracy with  different hyperparameter(optuna)
 ----------------------------------

# A.Example 1

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


In [5]:
# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
names = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"]
data = pd.read_csv(url, names=names)



age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
132  29.0  1.0  2.0     130.0  204.0  0.0      2.0    202.0    0.0      0.0   
202  57.0  1.0  3.0     150.0  126.0  1.0      0.0    173.0    0.0      0.2   
196  69.0  1.0  1.0     160.0  234.0  1.0      2.0    131.0    0.0      0.1   
75   65.0  0.0  3.0     160.0  360.0  0.0      2.0    151.0    0.0      0.8   
176  52.0  1.0  4.0     108.0  233.0  1.0      0.0    147.0    0.0      0.1   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
188  54.0  1.0  2.0     192.0  283.0  0.0      2.0    195.0    0.0      0.0   
71   67.0  1.0  4.0     125.0  254.0  1.0      0.0    163.0    0.0      0.2   
106  59.0  1.0  4.0     140.0  177.0  0.0      0.0    162.0    1.0      0.0   
270  61.0  1.0  4.0     140.0  207.0  0.0      2.0    138.0    1.0      1.9   
102  57.0  0.0  4.0     128.0  303.0  0.0      2.0    159.0    0.0      0.0   

     slope   ca thal  
132    1.0  0.0  3.0  
202    1.0  1.0  7.0  
196    2.0  1.0  3.0  
75     1.0  0.0  3.0  
176    1.0  3.0  7.0  
..     ...  ...  ...  
188    1.0  1.0  7.0  
71     2.0  2.0  7.0  
106    1.0  1.0  7.0  
270    1.0  1.0  7.0  
102    1.0  1.0  3.0  

[242 rows x 13 columns]

In [28]:
for i in data.columns:
    print(i,'#'*50,type(data[i][0]))
    print(data[i].unique())
    

age ################################################## <class 'numpy.float64'>
[63. 67. 37. 41. 56. 62. 57. 53. 44. 52. 48. 54. 49. 64. 58. 60. 50. 66.
 43. 40. 69. 59. 42. 55. 61. 65. 71. 51. 46. 45. 39. 68. 47. 34. 35. 29.
 70. 77. 38. 74. 76.]
sex ################################################## <class 'numpy.float64'>
[1. 0.]
cp ################################################## <class 'numpy.float64'>
[1. 4. 3. 2.]
trestbps ################################################## <class 'numpy.float64'>
[145. 160. 120. 130. 140. 172. 150. 110. 132. 117. 135. 112. 105. 124.
 125. 142. 128. 170. 155. 104. 180. 138. 108. 134. 122. 115. 118. 100.
 200.  94. 165. 102. 152. 101. 126. 174. 148. 178. 158. 192. 129. 144.
 123. 136. 146. 106. 156. 154. 114. 164.]
chol ################################################## <class 'numpy.float64'>
[233. 286. 229. 250. 204. 236. 268. 354. 254. 203. 192. 294. 256. 263.
 199. 168. 239. 275. 266. 211. 283. 284. 224. 206. 219. 340. 226. 247.
 167. 230. 33

In [38]:
#replace ? with MOST most frequest value
data['ca'] = data['ca'].str.replace('?',data['ca'].value_counts().idxmax(),regex=False)
data['thal'] = data['thal'].str.replace('?',data['thal'].value_counts().idxmax(),regex=False)
#recheck replacement
for i in data.columns:
    print(i,'#'*50)
    print(data[i].unique())


age ##################################################
[63. 67. 37. 41. 56. 62. 57. 53. 44. 52. 48. 54. 49. 64. 58. 60. 50. 66.
 43. 40. 69. 59. 42. 55. 61. 65. 71. 51. 46. 45. 39. 68. 47. 34. 35. 29.
 70. 77. 38. 74. 76.]
sex ##################################################
[1. 0.]
cp ##################################################
[1. 4. 3. 2.]
trestbps ##################################################
[145. 160. 120. 130. 140. 172. 150. 110. 132. 117. 135. 112. 105. 124.
 125. 142. 128. 170. 155. 104. 180. 138. 108. 134. 122. 115. 118. 100.
 200.  94. 165. 102. 152. 101. 126. 174. 148. 178. 158. 192. 129. 144.
 123. 136. 146. 106. 156. 154. 114. 164.]
chol ##################################################
[233. 286. 229. 250. 204. 236. 268. 354. 254. 203. 192. 294. 256. 263.
 199. 168. 239. 275. 266. 211. 283. 284. 224. 206. 219. 340. 226. 247.
 167. 230. 335. 234. 177. 276. 353. 243. 225. 302. 212. 330. 175. 417.
 197. 198. 290. 253. 172. 273. 213. 305. 216. 304. 188. 282. 1

In [39]:
# Preprocess the dataset
data = data.dropna()
X = data.drop("target", axis=1)
y = data["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
132  29.0  1.0  2.0     130.0  204.0  0.0      2.0    202.0    0.0      0.0   
202  57.0  1.0  3.0     150.0  126.0  1.0      0.0    173.0    0.0      0.2   
196  69.0  1.0  1.0     160.0  234.0  1.0      2.0    131.0    0.0      0.1   
75   65.0  0.0  3.0     160.0  360.0  0.0      2.0    151.0    0.0      0.8   
176  52.0  1.0  4.0     108.0  233.0  1.0      0.0    147.0    0.0      0.1   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
188  54.0  1.0  2.0     192.0  283.0  0.0      2.0    195.0    0.0      0.0   
71   67.0  1.0  4.0     125.0  254.0  1.0      0.0    163.0    0.0      0.2   
106  59.0  1.0  4.0     140.0  177.0  0.0      0.0    162.0    1.0      0.0   
270  61.0  1.0  4.0     140.0  207.0  0.0      2.0    138.0    1.0      1.9   
102  57.0  0.0  4.0     128.0  303.0  0.0      2.0    159.0    0.0      0.0   

     slope   ca thal  
132    1.0  0.0  3.0  
202    1.0  1.0  7.0  
196    2.0  1.0  3.0  
75     1.0  0.0  3.0  
176    1.0  3.0  7.0  
..     ...  ...  ...  
188    1.0  1.0  7.0  
71     2.0  2.0  7.0  
106    1.0  1.0  7.0  
270    1.0  1.0  7.0  
102    1.0  1.0  3.0  

[242 rows x 13 columns]

Function for Optuna optimization

In [40]:
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000, step=100),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
    }

    model = RandomForestClassifier(**params, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    return accuracy


Perform the hyperparameter search using Optuna:

In [41]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

best_params = study.best_params
best_accuracy = study.best_value

print("Best Parameters:", best_params)
print("Best Accuracy:", best_accuracy)


[I 2023-05-26 00:07:02,570] A new study created in memory with name: no-name-2a3c2804-d9cf-4fd8-9a2d-797f031729eb
[I 2023-05-26 00:07:06,624] Trial 0 finished with value: 0.5081967213114754 and parameters: {'n_estimators': 900, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.5081967213114754.
[I 2023-05-26 00:07:09,664] Trial 1 finished with value: 0.4918032786885246 and parameters: {'n_estimators': 700, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.5081967213114754.
[I 2023-05-26 00:07:13,181] Trial 2 finished with value: 0.5081967213114754 and parameters: {'n_estimators': 800, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.5081967213114754.
[I 2023-05-26 00:07:17,589] Trial 3 finished with value: 0.5081967213114754 and parameters: {'n_estimators': 1000, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value:

Best Parameters: {'n_estimators': 400, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 1}
Best Accuracy: 0.5409836065573771


# B.Example 2

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import optuna


In [48]:
# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
names = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"]
data = pd.read_csv(url, names=names)

data.head()



age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  target  
0    3.0  0.0  6.0       0  
1    2.0  3.0  3.0       2  
2    2.0  2.0  7.0       1  
3    3.0  0.0  3.0       0  
4    1.0  0.0  3.0       0

In [49]:
#replace ? with MOST most frequest value
data['ca'] = data['ca'].str.replace('?',data['ca'].value_counts().idxmax(),regex=False)
data['thal'] = data['thal'].str.replace('?',data['thal'].value_counts().idxmax(),regex=False)
#recheck replacement
for i in data.columns:
    print(i,'#'*50)
    print(data[i].unique())

age ##################################################
[63. 67. 37. 41. 56. 62. 57. 53. 44. 52. 48. 54. 49. 64. 58. 60. 50. 66.
 43. 40. 69. 59. 42. 55. 61. 65. 71. 51. 46. 45. 39. 68. 47. 34. 35. 29.
 70. 77. 38. 74. 76.]
sex ##################################################
[1. 0.]
cp ##################################################
[1. 4. 3. 2.]
trestbps ##################################################
[145. 160. 120. 130. 140. 172. 150. 110. 132. 117. 135. 112. 105. 124.
 125. 142. 128. 170. 155. 104. 180. 138. 108. 134. 122. 115. 118. 100.
 200.  94. 165. 102. 152. 101. 126. 174. 148. 178. 158. 192. 129. 144.
 123. 136. 146. 106. 156. 154. 114. 164.]
chol ##################################################
[233. 286. 229. 250. 204. 236. 268. 354. 254. 203. 192. 294. 256. 263.
 199. 168. 239. 275. 266. 211. 283. 284. 224. 206. 219. 340. 226. 247.
 167. 230. 335. 234. 177. 276. 353. 243. 225. 302. 212. 330. 175. 417.
 197. 198. 290. 253. 172. 273. 213. 305. 216. 304. 188. 282. 1

In [50]:

    
# Preprocess the dataset
data = data.dropna()
X = data.drop("target", axis=1)
y = data["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
#Define the objective function for Optuna optimization

In [51]:
def objective(trial):
    params = {
        'C': trial.suggest_loguniform('C', 0.1, 10.0),
        'kernel': trial.suggest_categorical('kernel', ['linear', 'rbf', 'sigmoid']),
        'gamma': trial.suggest_categorical('gamma', ['scale', 'auto'])        
    }

    model = SVC(**params, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    return accuracy


In [52]:
#Perform the hyperparameter search using Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

best_params = study.best_params
best_accuracy = study.best_value

print("Best Parameters:", best_params)
print("Best Accuracy:", best_accuracy)


[I 2023-05-26 00:16:30,855] A new study created in memory with name: no-name-ed93951b-94d4-491f-adac-ffbe9ed0f750
C:\Users\sujith.ks\AppData\Local\Temp\ipykernel_13940\3723450152.py:3: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  'C': trial.suggest_loguniform('C', 0.1, 10.0),
[I 2023-05-26 00:16:30,898] Trial 0 finished with value: 0.47540983606557374 and parameters: {'C': 0.11181634557721519, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.47540983606557374.
C:\Users\sujith.ks\AppData\Local\Temp\ipykernel_13940\3723450152.py:3: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  'C': trial.suggest_loguniform('C', 0.1, 10.0),
[I 20

Best Parameters: {'C': 0.30486199082250043, 'kernel': 'linear', 'gamma': 'auto'}
Best Accuracy: 0.5901639344262295
